//==================================================================================
//==================================================================================
// File: HardwareAndCo.cpp
// Description: Centralized initialization and management of PENDA
//              hardware resources and software components (TFT display, GUI,
//              DSP modules, etc.)
//
// Copyright (c) 2025-2026 DadDesign-Project.
//==================================================================================
//==================================================================================

#include "PersistentDefine.h"
#include "HardwareAndCoDefines.h"
#include "@options.h"
#include "@EffectsConfig.h"

//**********************************************************************************
// External handles (generated by CubeMX)
//**********************************************************************************
extern QSPI_HandleTypeDef hqspi;               // QSPI flash interface handle
extern SAI_HandleTypeDef  hsai_BlockA1;        // SAI block A1 for audio
extern SAI_HandleTypeDef  hsai_BlockB1;        // SAI block B1 for audio
extern DMA_HandleTypeDef  hdma_sai1_a;         // DMA for SAI A
extern DMA_HandleTypeDef  hdma_sai1_b;         // DMA for SAI B
extern SPI_HandleTypeDef  hspi1;               // SPI for display
extern DMA_HandleTypeDef  hdma_spi1_tx;        // DMA for SPI transmit
extern UART_HandleTypeDef huart1;              // UART for MIDI
extern DMA_HandleTypeDef  hdma_usart1_rx;      // DMA for UART receive
extern I2C_HandleTypeDef  hi2c2;			   // I2C for WM8731

//**********************************************************************************
// Global instances
//**********************************************************************************

// SDRAM
#include "AS4C16M32SB.h"

// Flash memory instance
#include "IS25LP064A.h"
DadDrivers::cIS25LP064A __Flash;

// Persistent storage instances
#include "cFlasherStorage.h"
QFLASH_FLASHER  DadPersistentStorage::cFlasherStorage __FlasherStorage;
#include "cBlockStorageManager.h"
QFLASH_TABSAVE  uint8_t      						  __TabSaveBlock[BLOCK_STORAGE_MEM_SIZE];
DadPersistentStorage::cBlockStorageManager            __BlockStorageManager(__TabSaveBlock);
// -------------------------------------------------------------------
// Persistent Target — reserved in QFLASH_LOADER flash section
QFLASH_LOADER uint8_t __LoaderInfo[QFLAH_SECTOR_SIZE];

// Display instance
#include "cDisplay.h"
DECLARE_DISPLAY(__Display);

// Switch instances
#include "cSwitch.h"
DadDrivers::cSwitch __Switch1;
DadDrivers::cSwitch __Switch2;

// Encoder instances
#include "cEncoder.h"
DadDrivers::cEncoder __Encoder1;
DadDrivers::cEncoder __Encoder2;
DadDrivers::cEncoder __Encoder3;
DadDrivers::cEncoder __Encoder0;

// SoftSPI instance
#include "cSoftSPI.h"
DadDrivers::cSoftSPI __SoftSPI;

// Dry/Wet instance
#include "cDryWet.h"
DadDrivers::cDryWet  __DryWet;

// Bypass on off manager
#include "cBypassOnOffManager.h"
DadGUI:: cOn_Off_Manager __BypassOnOffManagerImpl;
DadGUI::iBypassOnOffManager* __pBypassOnOffManager = &__BypassOnOffManagerImpl;

// MIDI interface instance
#include "cMidi.h"
DadDrivers::cMidi __Midi;

// GUI instance
#include "MainGUI.h"
DadGUI::cMainGUI __GUI;

// WM8731 management for Rev5
#include "cWM8731.h"
DadDrivers::cWM8731  __WM8731;


// MPU Config
extern void MPU_Config(void);

// Background layer declaration for display
DECLARE_LAYER(BackLayer, SCREEN_WIDTH, SCREEN_HEIGHT);

// Effect Instantiation
DECLARE_EFFECT;

// ********************************************************************
// Specific initialization for hardware revision 5:
// input and output signals are inverted compared to revision 7."
//extern DMA_HandleTypeDef hdma_sai1_a;

//extern DMA_HandleTypeDef hdma_sai1_b;

static uint32_t SAI1_client =0;

void HAL_SAIRev5_MspInit(SAI_HandleTypeDef* hsai)
{

  GPIO_InitTypeDef GPIO_InitStruct;
/* SAI1 */
    if(hsai->Instance==SAI1_Block_A)
    {
    /* Peripheral clock enable */
    if (SAI1_client == 0)
    {
       __HAL_RCC_SAI1_CLK_ENABLE();
    }
    SAI1_client ++;

    /**SAI1_A_Block_A GPIO Configuration
    PE2     ------> SAI1_MCLK_A
    PE4     ------> SAI1_FS_A
    PE5     ------> SAI1_SCK_A
    PE6     ------> SAI1_SD_A
    */
    GPIO_InitStruct.Pin = GPIO_PIN_2|GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF6_SAI1;
    HAL_GPIO_Init(GPIOE, &GPIO_InitStruct);

      /* Peripheral DMA init*/

    hdma_sai1_a.Instance = DMA1_Stream0;
    hdma_sai1_a.Init.Request = DMA_REQUEST_SAI1_A;
    // ===============================================
    // Change vs Rev7
    hdma_sai1_a.Init.Direction = DMA_PERIPH_TO_MEMORY;
    // ===============================================

    hdma_sai1_a.Init.PeriphInc = DMA_PINC_DISABLE;
    hdma_sai1_a.Init.MemInc = DMA_MINC_ENABLE;
    hdma_sai1_a.Init.PeriphDataAlignment = DMA_PDATAALIGN_WORD;
    hdma_sai1_a.Init.MemDataAlignment = DMA_MDATAALIGN_WORD;
    hdma_sai1_a.Init.Mode = DMA_CIRCULAR;
    hdma_sai1_a.Init.Priority = DMA_PRIORITY_HIGH;
    hdma_sai1_a.Init.FIFOMode = DMA_FIFOMODE_DISABLE;
    if (HAL_DMA_Init(&hdma_sai1_a) != HAL_OK)
    {
      Error_Handler();
    }

    /* Several peripheral DMA handle pointers point to the same DMA handle.
     Be aware that there is only one channel to perform all the requested DMAs. */
    __HAL_LINKDMA(hsai,hdmarx,hdma_sai1_a);

    __HAL_LINKDMA(hsai,hdmatx,hdma_sai1_a);

    }
    if(hsai->Instance==SAI1_Block_B)
    {
      /* Peripheral clock enable */
      if (SAI1_client == 0)
      {
       __HAL_RCC_SAI1_CLK_ENABLE();
      }
    SAI1_client ++;

    /**SAI1_B_Block_B GPIO Configuration
    PE3     ------> SAI1_SD_B
    */
    GPIO_InitStruct.Pin = GPIO_PIN_3;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF6_SAI1;
    HAL_GPIO_Init(GPIOE, &GPIO_InitStruct);

      /* Peripheral DMA init*/

    hdma_sai1_b.Instance = DMA1_Stream1;
    hdma_sai1_b.Init.Request = DMA_REQUEST_SAI1_B;
    // ===============================================
    // Change vs Rev7
    hdma_sai1_b.Init.Direction = DMA_MEMORY_TO_PERIPH;
    //================================================

    hdma_sai1_b.Init.PeriphInc = DMA_PINC_DISABLE;
    hdma_sai1_b.Init.MemInc = DMA_MINC_ENABLE;
    hdma_sai1_b.Init.PeriphDataAlignment = DMA_PDATAALIGN_WORD;
    hdma_sai1_b.Init.MemDataAlignment = DMA_MDATAALIGN_WORD;
    hdma_sai1_b.Init.Mode = DMA_CIRCULAR;
    hdma_sai1_b.Init.Priority = DMA_PRIORITY_LOW;
    hdma_sai1_b.Init.FIFOMode = DMA_FIFOMODE_DISABLE;
    if (HAL_DMA_Init(&hdma_sai1_b) != HAL_OK)
    {
      Error_Handler();
    }

    /* Several peripheral DMA handle pointers point to the same DMA handle.
     Be aware that there is only one channel to perform all the requested DMAs. */
    __HAL_LINKDMA(hsai,hdmarx,hdma_sai1_b);
    __HAL_LINKDMA(hsai,hdmatx,hdma_sai1_b);
    }
}

// ------------------------------------------------------------------------
// Specific initialization for hardware revision 5:
// input and output signals are inverted compared to revision 7."
// ------------------------------------------------------------------------
void MX_SAI1Rev5_Init(void)
{
  HAL_SAI_RegisterCallback(&hsai_BlockA1, HAL_SAI_MSPINIT_CB_ID,HAL_SAIRev5_MspInit);
  HAL_SAI_RegisterCallback(&hsai_BlockB1, HAL_SAI_MSPINIT_CB_ID,HAL_SAIRev5_MspInit);

  hsai_BlockA1.Instance = SAI1_Block_A;
  // ===============================================
  // Change TX->RX
  hsai_BlockA1.Init.AudioMode = SAI_MODEMASTER_RX;
  // ===============================================
  hsai_BlockA1.Init.Synchro = SAI_ASYNCHRONOUS;
  hsai_BlockA1.Init.OutputDrive = SAI_OUTPUTDRIVE_DISABLE;
  hsai_BlockA1.Init.NoDivider = SAI_MCK_OVERSAMPLING_DISABLE;
  hsai_BlockA1.Init.MckOverSampling = SAI_MCK_OVERSAMPLING_DISABLE;
  hsai_BlockA1.Init.FIFOThreshold = SAI_FIFOTHRESHOLD_EMPTY;
  hsai_BlockA1.Init.AudioFrequency = SAI_AUDIO_FREQUENCY_48K;
  hsai_BlockA1.Init.SynchroExt = SAI_SYNCEXT_DISABLE;
  hsai_BlockA1.Init.MonoStereoMode = SAI_STEREOMODE;
  hsai_BlockA1.Init.CompandingMode = SAI_NOCOMPANDING;
  hsai_BlockA1.Init.TriState = SAI_OUTPUT_NOTRELEASED;
  if (HAL_SAI_InitProtocol(&hsai_BlockA1, SAI_I2S_MSBJUSTIFIED, SAI_PROTOCOL_DATASIZE_24BIT, 2) != HAL_OK)
  {
    Error_Handler();
  }
  hsai_BlockB1.Instance = SAI1_Block_B;
  // ===============================================
  // Change RC->TX
  hsai_BlockB1.Init.AudioMode = SAI_MODESLAVE_TX;
  // ===============================================
  hsai_BlockB1.Init.Synchro = SAI_SYNCHRONOUS;
  hsai_BlockB1.Init.OutputDrive = SAI_OUTPUTDRIVE_DISABLE;
  hsai_BlockB1.Init.MckOverSampling = SAI_MCK_OVERSAMPLING_DISABLE;
  hsai_BlockB1.Init.FIFOThreshold = SAI_FIFOTHRESHOLD_EMPTY;
  hsai_BlockB1.Init.SynchroExt = SAI_SYNCEXT_DISABLE;
  hsai_BlockB1.Init.MonoStereoMode = SAI_STEREOMODE;
  hsai_BlockB1.Init.CompandingMode = SAI_NOCOMPANDING;
  hsai_BlockB1.Init.TriState = SAI_OUTPUT_NOTRELEASED;
  if (HAL_SAI_InitProtocol(&hsai_BlockB1, SAI_I2S_MSBJUSTIFIED, SAI_PROTOCOL_DATASIZE_24BIT, 2) != HAL_OK)
  {
    Error_Handler();
  }
}

// ------------------------------------------------------------------------
// Standard MX initialization for hardware revision 7
// ------------------------------------------------------------------------
extern void MX_SAI1_Init(void);

//**********************************************************************************
// HardwareAndCoInitialize
// Initializes all hardware peripherals in the correct order
//**********************************************************************************
void HardwareAndCoInitialize() {
	// Daisy seed revision
	eHardRev_t DaisyRev;

	// Initialize SDRAM memory
	AS4C16M32SB_Initialize();

    // Initialize QSPI flash memory
    if (HAL_OK != __Flash.Init(&hqspi, DOUBLE_MODE, FLASH_ADDRESS)) {
        Error_Handler();
    }

    // Configure Memory Protection Unit
    MPU_Config();

    // Invalidate CPU caches for memory consistency
    SCB_InvalidateDCache();
    SCB_InvalidateICache();

    // Initialize SAI
    if(GPIO_PIN_RESET == HAL_GPIO_ReadPin(Rev5_GPIO_Port, Rev5_Pin)){
      DaisyRev = eHardRev_t::Rev5;
  	  MX_I2C2_Init();
  	  MX_SAI1Rev5_Init();
  	  __WM8731.Initialize(&hi2c2);
    }else if(GPIO_PIN_RESET == HAL_GPIO_ReadPin(Rev7_GPIO_Port, Rev7_Pin)){
      DaisyRev = eHardRev_t::Rev7;
  	  MX_SAI1_Init();

  	  GPIO_InitTypeDef GPIO_InitStruct = {0};
  	  GPIO_InitStruct.Pin = GPIO_PIN_11;
  	  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  	  GPIO_InitStruct.Pull = GPIO_NOPULL;
  	  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  	  HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
  	  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, GPIO_PIN_RESET);

    }else{
  	  // Revision not supported
  	  while(1){
  	     HAL_GPIO_TogglePin(LED_GPIO_Port, LED_Pin);
  		 HAL_Delay(100);
  	  }
    }

	// Initialize persistent storage and check if initialization is needed
    bool NeedInitBlockStorage = __BlockStorageManager.Init(EFFECT_BUILD);

    // Initialize display
    INIT_DISPLAY(__Display, &hspi1);
    __Display.setOrientation(Rotation::Degre_90);

    // Initialize GUI system
    __GUI.Initialize();

    // Initialize foot switches with debouncing parameters
    constexpr uint32_t kUpdateTime      = static_cast<uint32_t>(RT_RATE * 0.03f);   // 30ms debounce
    constexpr uint32_t kMinPeriod       = static_cast<uint32_t>(RT_RATE * 0.15f);   // 150ms min valid press
    constexpr uint32_t kMaxPeriod       = static_cast<uint32_t>(RT_RATE * 1.1f);    // 1.1s max hold
    constexpr uint32_t kAbortMaxPeriod  = static_cast<uint32_t>(RT_RATE * 1.5f);    // 1.5s timeout

    __Switch1.Init(FootSwitch1_GPIO_Port, FootSwitch1_Pin,
                   RT_RATE, kUpdateTime, kMinPeriod, kMaxPeriod, kAbortMaxPeriod);

    __Switch2.Init(FootSwitch2_GPIO_Port, FootSwitch2_Pin,
                   RT_RATE, kUpdateTime, kMinPeriod, kMaxPeriod, kAbortMaxPeriod);

    // Initialize rotary encoders
    constexpr uint32_t EncoderUpdatePeriodMs = RT_RATE * 0.001f; // 1ms update
    constexpr uint32_t SwitchUpdatePeriodMs  = RT_RATE * 0.005f; // 5ms switch check

    __Encoder3.Init(Encoder1_A_GPIO_Port, Encoder1_A_Pin,
                    Encoder1_B_GPIO_Port, Encoder1_B_Pin,
                    Encoder1_SW_GPIO_Port, Encoder1_SW_Pin,
                    EncoderUpdatePeriodMs, SwitchUpdatePeriodMs);

    __Encoder2.Init(Encoder2_A_GPIO_Port, Encoder2_A_Pin,
                    Encoder2_B_GPIO_Port, Encoder2_B_Pin,
                    Encoder2_SW_GPIO_Port, Encoder2_SW_Pin,
                    EncoderUpdatePeriodMs, SwitchUpdatePeriodMs);

    __Encoder1.Init(Encoder3_A_GPIO_Port, Encoder3_A_Pin,
                    Encoder3_B_GPIO_Port, Encoder3_B_Pin,
                    Encoder3_SW_GPIO_Port, Encoder3_SW_Pin,
                    EncoderUpdatePeriodMs, SwitchUpdatePeriodMs);

    __Encoder0.Init(Encoder0_A_GPIO_Port, Encoder0_A_Pin,
                    Encoder0_B_GPIO_Port, Encoder0_B_Pin,
                    Encoder0_SW_GPIO_Port, Encoder0_SW_Pin,
                    EncoderUpdatePeriodMs, SwitchUpdatePeriodMs);

    __DryWet.Init(MIN_DRY, MAX_DRY, FAD_TIME);
    __pBypassOnOffManager->Initialize();

    __Midi.Initialize(&huart1, 0);


    // Load and display splash screen from flash
    uint8_t* ImgPtr;
    uint8_t  NbFrame;
    uint16_t Width;
    uint16_t Height;
    __FlasherStorage.GetImgInformation(EFFECT_SPLATCH_SCREEN, ImgPtr, NbFrame, Width, Height);
    DadGFX::cImageLayer* SplatchLayer = nullptr;

    if(ImgPtr){
        SplatchLayer = __Display.addLayer(ImgPtr, 0, 0, Width, Height, 1, NbFrame);
        SplatchLayer->changeZOrder(2);
    }

    // Create background layer for initialization messages
    DadGFX::cLayer* BackLayer = ADD_LAYER(__Display, BackLayer, 0, 0, 2);
    BackLayer->changeZOrder(3);
    BackLayer->eraseLayer();
    __Display.flush();

    // Display initialization message if storage needs initialization
    if(NeedInitBlockStorage){
        constexpr uint16_t WidthBox = 200;
        constexpr uint16_t HeightBox = 120;
        constexpr uint16_t xBox = (SCREEN_WIDTH - WidthBox ) / 2;
        constexpr uint16_t yBox = (SCREEN_HEIGHT - HeightBox) / 2;
        constexpr uint16_t xHalfBox = SCREEN_WIDTH / 2;
        constexpr uint16_t yHalfBox = SCREEN_HEIGHT / 2;
        constexpr uint16_t yOffset = 50;

        const char* Text1 = "Please wait...";
        const char* Text2 = "Initializing";
        const char* Text3 = "flash memory.";

        // Draw initialization dialog box
        BackLayer->drawFillRect(xBox, yBox, WidthBox, HeightBox, DadGUI::__ThemesManager->SplatchBack);

        // Display initialization text
        BackLayer->setFont(FONTMB);
        uint16_t TextWidth = BackLayer->getTextWidth(Text1);
        BackLayer->setCursor(xHalfBox - TextWidth/2, yHalfBox - yOffset);
        BackLayer->setTextFrontColor(DadGUI::__ThemesManager->SplatchText);
        BackLayer->drawText(Text1);

        BackLayer->setFont(FONTS);
        TextWidth = BackLayer->getTextWidth(Text2);
        BackLayer->setCursor(xHalfBox - TextWidth/2, yHalfBox);
        BackLayer->setTextFrontColor(DadGUI::__ThemesManager->SplatchText);
        BackLayer->drawText(Text2);

        TextWidth = BackLayer->getTextWidth(Text3);
        BackLayer->setCursor(xHalfBox - TextWidth/2, yHalfBox + 20);
        BackLayer->setTextFrontColor(DadGUI::__ThemesManager->SplatchText);
        BackLayer->drawText(Text3);

        __Display.flush();

        // Initialize flash memory storage
        __BlockStorageManager.InitializeMemory(EFFECT_BUILD);
        HAL_Delay(400);
    } else {
        __Display.flush();
        HAL_Delay(1000);
    }

    // Clean up initialization layers
    BackLayer->changeZOrder(0);
    if(SplatchLayer){
        SplatchLayer->changeZOrder(0);
    }


    // Initialize audio effect processing
    __Effect.Initialize();

    // Start GUI system
    __GUI.Start();

    // Start audio processing engine
    if(DaisyRev == eHardRev_t::Rev5){
		if (HAL_OK != StartAudio(&hsai_BlockB1, &hsai_BlockA1)) {
			Error_Handler();
		}
    }else{
		if (HAL_OK != StartAudio(&hsai_BlockA1, &hsai_BlockB1)) {
			Error_Handler();
		}
    }

    // Start GUI system
    __GUI.MainLoop();
}

// =============================================================================
// Real-time Audio Processing
// =============================================================================

//**********************************************************************************
// AudioCallback
// Real-time audio processing function executed by the audio engine
//**********************************************************************************
void AudioCallback(AudioBuffer *pIn, AudioBuffer *pOut) {

#ifdef MONITOR
    __GUI.startRTMonitoring(); // Start performance monitoring
#endif

    // Update activity counter for LED heartbeat
    __GUI.notifyRTActivity();

    // Update all input devices in real-time
    __Switch1.Debounce();
    __Switch2.Debounce();
    __Encoder1.Debounce();
    __Encoder2.Debounce();
    __Encoder3.Debounce();
    __Encoder0.Debounce();

    // Process audio buffer samples
    for (size_t i = 0; i < AUDIO_BUFFER_SIZE; i++) {
    	bool Silence = ((fabs(pIn->Right) + fabs(pIn->Left)) < 0.01f);

        // Process audio through GUI and effect chain
        DadGUI::__GUI_EventManager.sendEventToActive_RT_ProcessIn(pIn);
        __Effect.Process(pIn, pOut, __pBypassOnOffManager->getTargetState(), Silence);
        DadGUI::__GUI_EventManager.sendEventToActive_RT_Process();
        DadGUI::__GUI_EventManager.sendEventToActive_RT_ProcessOut(pOut);

        // Advance buffer pointers
        pOut++;
        pIn++;
    }

#ifdef MONITOR
    __GUI.stopRTMonitoring(); // Stop performance monitoring
#endif
}


//***End of file**************************************************************




